# GitHub Action to compile QMK firmware for a Corne keyboard
#
# How to use:
# 1. Create a directory in your repository named `.github/workflows`
# 2. Create a new file inside that directory named `build-firmware.yml`
# 3. Copy and paste the contents of this file into `build-firmware.yml`
# 4. **Important:** Update the placeholder values in the "Compile Firmware" step
#    to match your specific keyboard and keymap folder name.
# 5. Commit and push the changes. The action will run on the next push.

name: 'Build Corne Firmware'

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main, master ]

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  build:
    # Use the official QMK CLI Docker container which has the build environment pre-configured.
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      # Step 1: Check out your repository code
      # This makes your keymap folder available to the workflow.
      - name: 'Check out repository'
        uses: actions/checkout@v4

      # Step 2: Compile the firmware
      # The QMK environment is already set up inside the Docker container.
      # This step links your local keymap folder into the container's QMK firmware
      # directory and then runs the compile command.
      #
      # ----------------- VERY IMPORTANT -----------------
      # You MUST change the KEYMAP_NAME and KEYBOARD_PATH to match your setup.
      #
      # KEYMAP_NAME:   The name of YOUR keymap folder in this repository.
      # KEYBOARD_PATH: The path to your keyboard in QMK. For a Corne, `crkbd/rev1` is common.
      # ----------------------------------------------------
      - name: 'Compile Firmware'
        run: |
          # Set your keymap and keyboard path here
          KEYMAP_NAME="YOUR_KEYMAP_FOLDER_NAME" # <-- CHANGE THIS
          KEYBOARD_PATH="crkbd/rev1"             # <-- CHANGE THIS if needed

          # Link your keymap folder (from your repo checkout) into the QMK keyboards directory inside the container.
          # The QMK firmware source is at /qmk_firmware in the container.
          # Your checked-out code is at $GITHUB_WORKSPACE.
          ln -s "$GITHUB_WORKSPACE" "/qmk_firmware/keyboards/$KEYBOARD_PATH/keymaps/$KEYMAP_NAME"

          # Run the QMK compile command
          qmk compile -kb "$KEYBOARD_PATH" -km "$KEYMAP_NAME"

      # Step 3: Upload the compiled firmware as a build artifact
      # This makes the final .uf2 file available for download from the GitHub Actions run summary page.
      - name: 'Upload Firmware Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: corne-firmware # The name of the downloadable artifact zip file
          path: /qmk_firmware/*.uf2 # Path to the compiled file inside the container. Change .uf2 if your board uses .hex, .bin, etc.
